name: Bug report
description: Report a bug or regression.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect to happen?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Include code snippets or commands if relevant.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs, error messages, or backtraces.
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide versions and OS details.
      placeholder: |
        - OS:
        - Rust version (rustc -V):
        - Cargo version (cargo -V):
        - my_curl version/commit:
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or other relevant info.
